[package]
name = "defenestrate-core"
version = "0.1.0"
authors = ["Joe Quigley <quigley.joseph@outlook.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitflags = "1.0"
wasm-bindgen="0.2"
